# Generated by Django 4.0.3 on 2022-04-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='telegramm',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
