# Generated by Django 4.0.3 on 2022-04-21 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_create', models.DateTimeField()),
                ('robot_type', models.CharField(max_length=100)),
                ('camera_type', models.CharField(max_length=100)),
                ('commentary', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.account')),
            ],
            options={
                'db_table': 'flying',
            },
        ),
        migrations.CreateModel(
            name='FlyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('fly', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controll_pkg.fly')),
            ],
            options={
                'db_table': 'fly_image',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('at_create', models.DateTimeField()),
                ('at_update', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.account')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ObservationObjectChronology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_create', models.DateTimeField()),
                ('at_update', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('coordinate', models.CharField(max_length=100)),
                ('commentary', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.account')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controll_pkg.project')),
            ],
            options={
                'db_table': 'observation_object_chronology',
            },
        ),
        migrations.CreateModel(
            name='ObservationObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_create', models.DateTimeField()),
                ('image_box', models.CharField(max_length=100)),
                ('commentary', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.account')),
                ('chronology', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controll_pkg.observationobjectchronology')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controll_pkg.flyimage')),
            ],
            options={
                'db_table': 'observation_object',
            },
        ),
        migrations.AddField(
            model_name='fly',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controll_pkg.project'),
        ),
    ]
