# Generated by Django 4.0.3 on 2022-04-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll_pkg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flyimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
