# Generated by Django 4.0.3 on 2022-04-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll_pkg', '0002_fly_name_alter_flyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='at_fly',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
