# Generated by Django 4.0.3 on 2022-06-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll_pkg', '0008_alter_fly_camera_type_alter_fly_commentary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='images_coords',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
    ]
