# Generated by Django 4.0.3 on 2022-06-17 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_account_telegramm'),
        ('controll_pkg', '0009_fly_images_coords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.account'),
        ),
    ]
