# Generated by Django 4.0.3 on 2022-06-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_account_telegramm'),
        ('controll_pkg', '0010_alter_project_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='author',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.account'),
        ),
        migrations.AlterField(
            model_name='fly',
            name='project',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='controll_pkg.project'),
        ),
    ]
