# Generated by Django 4.0.3 on 2022-06-18 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_account_telegramm'),
        ('controll_pkg', '0011_alter_fly_author_alter_fly_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='author',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.account'),
        ),
        migrations.AlterField(
            model_name='fly',
            name='project',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controll_pkg.project'),
        ),
        migrations.AlterField(
            model_name='flyimage',
            name='fly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controll_pkg.fly'),
        ),
        migrations.AlterField(
            model_name='observationobject',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.account'),
        ),
        migrations.AlterField(
            model_name='observationobject',
            name='chronology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controll_pkg.observationobjectchronology'),
        ),
        migrations.AlterField(
            model_name='observationobject',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controll_pkg.flyimage'),
        ),
        migrations.AlterField(
            model_name='observationobjectchronology',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.account'),
        ),
        migrations.AlterField(
            model_name='observationobjectchronology',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controll_pkg.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.account'),
        ),
    ]
