# Generated by Django 4.0.3 on 2022-06-18 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controll_pkg', '0012_alter_fly_author_alter_fly_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationobject',
            name='chronology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controll_pkg.observationobjectchronology'),
        ),
        migrations.AlterField(
            model_name='observationobject',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controll_pkg.flyimage'),
        ),
        migrations.AlterField(
            model_name='observationobjectchronology',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controll_pkg.project'),
        ),
    ]
